# Generated by Django 3.2.4 on 2021-06-05 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_match_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
