# Generated by Django 3.2.4 on 2021-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_match_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.URLField(default='')),
            ],
        ),
    ]
