# Generated by Django 3.2.4 on 2021-06-06 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TypePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='noname', max_length=100)),
                ('last_name', models.CharField(default='noname', max_length=100)),
                ('number', models.PositiveIntegerField(default=0)),
                ('decs', models.TextField(default='')),
                ('years', models.PositiveIntegerField(default=0)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('team', models.CharField(choices=[('M', 'Основа'), ('A', 'Академія')], max_length=20)),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='club.nationality')),
                ('type_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='club.typeplayer')),
            ],
        ),
    ]
