# Generated by Django 3.2.4 on 2021-06-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_nationality_player_typeplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.ImageField(default='gaga.jpeg', upload_to=''),
        ),
    ]
