# Generated by Django 3.2.4 on 2021-06-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20210606_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='years',
        ),
    ]
