# Generated by Django 3.2.4 on 2021-06-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_auto_20210607_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='admin_title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
